# Generated by Django 5.1.6 on 2025-02-22 19:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_groups_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estado',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', verbose_name='Telefone'),
        ),
    ]
