# Generated by Django 5.1.6 on 2025-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_imovel_cidade_alter_imovel_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(related_name='usuario_groups', to='auth.group'),
        ),
    ]
